---

# This file hold the definiton of the host to manage with Ansible

common:
  hosts:
    prometeo:
      ansible_host: 192.168.167.151
      ansible_connection: ssh
# Disable because this host hold already the basic tools
#    ansiblix:
#      ansible_host: 192.168.167.12
#      ansible_connection: local

mgmt:
  hosts:
    ansiblix:
      ansible_host: 192.168.167.12
      ansible_connection: local

