---

# This is the principal file for the ansible deploy's

- name: Install general tools
  hosts: common #all
  remote_user: root
  gather_facts: False
  roles:
    - common

- name: Install puppet tools
  hosts: mgmt
  remote_user: root
  gather_facts: False
  roles:
    - mgmt-puppet

